VirtualRobotConfig: {
  panda1:
  {
    interaction_method: "real_robot",
    # interaction_method: "virtual_robot",
    # interaction_method: "hand_tracking",
    # interaction_method: "gamepad",
    # interaction_method: "motion_controller",
  },
  panda2:
  {
    interaction_method: "real_robot",
    # interaction_method: "virtual_robot",
    # interaction_method: "hand_tracking",
    # interaction_method: "gamepad",
    # interaction_method: "motion_controller",
  },
}

RealRobotConfig: {
  panda1:
  {
    # IRL Setting
    #sl_robot_name: panda201,
    #backend_addr: tcp://10.10.10.210:51201,
    #local_addr: 10.10.10.220,
    # ALR Setting
    ip: "141.3.53.152",
    robot_port: "1234", 
    gripper_port: "1235", 
  },
  panda2:
  {
    # IRL Setting
    # robot_name: panda201,
    # backend_addr: tcp://10.10.10.210:51201,
    # local_addr: 10.10.10.220,
    # ALR Setting
    ip: "141.3.53.152",
    robot_port: "4321", 
    gripper_port: "4322", 
  },
}

HDARConfig: {
  # host: "192.168.178.102",
  host: "192.168.0.143",
  # host: 192.168.122.1,
  # host: "192.168.0.215",
  # host: "192.168.0.215", # virtual robot test
  # host: "192.168.0.246",
  # host: "10.42.0.1", # irl-220 hot spot
  # host: 141.3.53.54,
  port: 8052,
}


QRConfig: {
  QRText: "SFBase",
  offsetPos: [-0.72,  -0.19, 0.015],
  offsetRot: [-90.0, 180.0, 0.0],
}

SimulatorConfig: {
  # task_type: "grasp_object",
  task_type: "bimanual_test",
  # task_type: "box_stacking2",
  # task_type: "object_passing",
  # task_type: "box_passing",
  # task_type: "hole_stick",
  # task_type: "cube_stacking",
  # task_type: "warm_up",
  # task_type: "cup_stacking",
  # task_type: "practical_manipulation",
  # task_type: "box_stacking",
  # task_type: "user_study",
  record_mode: True,
  time_limit: 10000,
  dt: 0.002,
  downsample_steps: 10,
}