# task: grasp_object,
# task: bimanual_test,
# task: stacking,
# task: cube_stacking,
# task: warm_up,
# task: box_stacking,
# task: cup_stacking,
task: practical_manipulation,

RecorderConfig: {
  record_mode: False,
  downsample_steps: 1,
}

RobotConfig: {
  grasp_robot:
  {
    # interaction: real_robot,
    # interaction: virtual_robot,
    interaction: hand_tracking,
    # interaction: gamepad,
    # interaction: motion_controller,
    auto_recorder: true
  },
}

SLConfig: {
  grasp_robot:
  {
    # IRL Setting
    sl_robot_name: panda201,
    backend_addr: tcp://10.10.10.210:51201,
    local_addr: 10.10.10.220,
    
    # ALR Setting
    # sl_robot_name: panda2,
    # backend_addr: tcp://141.3.53.152:51102,
    # local_addr: 141.3.53.158,
  }
}

ServerConfig: {
  # hdar_addr: 192.168.178.102,
  # hdar_addr: 192.168.0.143,
  server_addr: 192.168.0.215,
  # hdar_addr: 192.168.0.215, # virtual robot test
  # hdar_addr: 192.168.0.246,
  # hdar_addr: 10.42.0.1, # irl-220 hot spot
  # hdar_addr: 141.3.53.54,
  server_port: 8052,
}


AnchorQRConfig: {
  QRText: SFBase,
  offsetPos: [0.045,  -0.14, 0.005],
  # offsetPos: [0.0,  0.0, 0.5],
  offsetRot: [-90.0, 179.0, 0.0],
}