task_type: grasp test
discription: grasp test

robots:
  {
    panda1: {
      base_position: [0.0, 0.0, 0.0],
      base_rotation: [0.0, 0.0, 0.0],
      init_end_eff_pos: [0.525, 0.0, 0.3],
      init_end_eff_quat: [0.0, 1.0, 0.0, 0.0],
    },
  }

objects: 
  {
    target: {
      type: Box,
      source: primitive_object,
      init_pos: [0.3, -0.2, 0.0],
      init_quat: [0.0, 1.0, 0.0, 0.0],
      rgba: [1.0, 0.0, 0.0, 1.0],
      mass: 0.05,
      size: [0.02, 0.02, 0.03],
    }, 
    aim1: 
        {
          type: Box,
          source: primitive_object,
          init_pos: [0.375, 0.2, 0.1],
          init_quat: [0.0, 0.0, 0.0, 1.0],
          rgba: [0.5, 0.0, 0.5, 0.6],
          size: [0.07, 0.025, 0.2],
          mass: 0.05,
          # visual_only: True,
          static: True,
        },
    aim2: {
          type: Box,
          source: primitive_object,
          init_pos: [0.375, 0.275, 0.34],
          init_quat: [0.0, 1.0, 0.0, 0.0],
          rgba: [0.5, 0.0, 0.5, 0.6],
          size: [0.03, 0.025, 0.06],
          mass: 0.05,
          # visual_only: True,
          static: True,
        },
    aim3:{
          type: Box,
          source: primitive_object,
          init_pos: [0.3875, 0.275 , 0.24],
          init_quat: [0.0, 1.0, 0.0, 0.0],
          rgba: [0.5, 0.0, 0.5, 0.6],
          size: [0.025, 0.01, 0.025],
          mass: 0.05,
          # visual_only: True,
          static: True,
        },    
    aim4:{
          type: Box,
          source: primitive_object,
          init_pos: [0.3625, 0.275, 0.24],
          init_quat: [0.0, 1.0, 0.0, 0.0],
          rgba: [0.5, 0.0, 0.5, 0.6],
          size: [0.025, 0.01, 0.025],
          mass: 0.05,
          # visual_only: True,
          static: True,
        },
    
  }

