task_type: warm_up
discription: warm_up

robots:
  {
    panda1: {
      base_position: [0.0, 0.0, 0.0],
      base_rotation: [0.0, 0.0, 0.0],
      init_end_eff_pos: [0.525, 0.0, 0.3],
      init_end_eff_quat: [0.0, 1.0, 0.0, 0.0],
    },
  }

objects: 
  {
    strawberry: {
      type: 012_strawberry,
      init_pos: [0.5, 0.3, 0.2],
      init_quat: [1.0, 0.0, 0.0, 0.0],
      source: ycb,
    },
    # apple: {
    #   type: 013_apple,
    #   init_pos: [0.53, 0.2, 0.15],
    #   init_quat: [1.0, 0.0, 0.0, 0.0],
    #   source: ycb,
    # },
    plate: {
      type: 029_plate,
      init_pos: [0.5, 0.3, 0.1],
      init_quat: [1.0, 0.0, 0.0, 0.0],
      source: ycb,
    },
    mug: {
      type: 025_mug,
      init_pos: [0.5, -0.3, 0.1],
      init_quat: [0.0, 1.0, 0.0, 0.0],
      source: ycb,
    },
    green_box: {
      type: Box,
      init_pos: [0.35, -0.1, 0.0],
      init_quat: [0.0, 1.0, 0.0, 0.0],
      rgba: [0.0, 1.0, 0.0, 1.0],
      mass: 0.05,
      size: [0.03, 0.03, 0.03],
      source: primitive_object,
    },
    blue_box: {
      type: Box,
      init_pos: [0.55, -0.25, 0.0],
      init_quat: [0.0, 1.0, 0.0, 0.0],
      rgba: [0.0, 0.0, 1.0, 1.0],
      mass: 0.05,
      size: [0.03, 0.05, 0.03],
      source: primitive_object,
    },
    d_cups: {
      type: 065-d_cups,
      init_pos: [0.6, -0.0, 0.0],
      init_quat: [1.0, 0.0, 0.0, 0.0],
      source: ycb,
    },
    # h_cups-1: {
    #   type: 065-h_cups,
    #   init_pos: [0.45, -0.1, 0.0],
    #   init_quat: [1.0, 0.0, 0.0, 0.0],
    #   source: ycb,
    # },
    f_cups: {
      type: 065-f_cups,
      init_pos: [0.6, 0.0, 0.0],
      init_quat: [1.0, 0.0, 0.0, 0.0],
      source: ycb,
    },
  }
